# -*- coding: utf-8 -*-
"""Kelompok Data Mining

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AEjWltG1bKnl7b8iPih_syW7THFVkeT8

TAHAP 1: Persiapan Lingkungan Analisis
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import silhouette_score, davies_bouldin_score
from sklearn.decomposition import PCA
import plotly.express as px
import plotly.graph_objects as go
import warnings
warnings.filterwarnings('ignore')

"""**Interpretasi:**
Tahap ini menyiapkan semua library yang dibutuhkan untuk analisis clustering. Google Colab sudah memiliki sebagian besar library ini, kecuali plotly yang perlu diinstall terlebih dahulu. Library scikit-learn menyediakan fungsi K-Means, normalisasi Min-Max, dan metrik evaluasi seperti Silhouette Score serta Davies-Bouldin Index. Library plotly digunakan untuk membuat radar plot interaktif.
"""

from google.colab import files
print("Upload file Excel: DATA MINING.xlsx")
uploaded = files.upload()

"""TAHAP 2: Load Data dari Excel"""

import io
filename = list(uploaded.keys())[0]

# Baca file Excel, skip 2 baris pertama (karena header ganda)
df_raw = pd.read_excel(io.BytesIO(uploaded[filename]), sheet_name='FIX', skiprows=1)

print(f"Data loaded: {df_raw.shape[0]} baris, {df_raw.shape[1]} kolom")
print("\n5 data pertama:")
df_raw.head()

"""TAHAP 3: Persiapan dan Pembersihan Data

Daftar Kolom
"""

print("Daftar kolom:")
print(df_raw.columns.tolist())

"""Rename Kolom (Sesuai Posisi)"""

# Berdasarkan urutan kolom di file Excel Anda
# Kolom ke-0: No, ke-1: Provinsi, ke-2: Kondisi Kelas SD, ke-3: Kondisi Kelas SMP, dst.
df_raw.columns = ['No', 'Provinsi',
                  'KondisiKelas_SD', 'KondisiKelas_SMP', 'KondisiKelas_SMA', 'KondisiKelas_SMK',
                  'Air_SD', 'Air_SMP', 'Air_SMA', 'Air_SMK',
                  'ToiletSD_Terpisah', 'ToiletSD_Bersama',
                  'ToiletSMP_Terpisah', 'ToiletSMP_Bersama',
                  'ToiletSMA_Terpisah', 'ToiletSMA_Bersama',
                  'ToiletSMK_Terpisah', 'ToiletSMK_Bersama',
                  'Rasio_SD', 'Rasio_SMP', 'Rasio_SMA', 'Rasio_SMK',
                  'Telepon', 'Komputer', 'Internet']

print("Kolom berhasil di-rename")
df_raw.head(40)

"""Bersihkan Data (Hapus Baris Kosong)"""

# Hapus baris yang Provinsi-nya kosong atau bukan string
df_raw = df_raw.dropna(subset=['Provinsi'])
df_raw = df_raw[df_raw['Provinsi'].astype(str).str.len() > 1]

# Reset index
df_raw = df_raw.reset_index(drop=True)

print(f"Jumlah provinsi: {len(df_raw)}")
df_raw[['No', 'Provinsi']].head()

"""Konversi ke Numerik"""

# Kolom yang perlu dikonversi ke numerik
kolom_numerik = ['KondisiKelas_SD', 'KondisiKelas_SMP', 'KondisiKelas_SMA', 'KondisiKelas_SMK',
                 'Air_SD', 'Air_SMP', 'Air_SMA', 'Air_SMK',
                 'ToiletSD_Terpisah', 'ToiletSMP_Terpisah', 'ToiletSMA_Terpisah', 'ToiletSMK_Terpisah',
                 'Rasio_SD', 'Rasio_SMP', 'Rasio_SMA', 'Rasio_SMK',
                 'Telepon', 'Komputer', 'Internet']

for col in kolom_numerik:
    df_raw[col] = pd.to_numeric(df_raw[col], errors='coerce')

print("Data berhasil dikonversi ke numerik")
df_raw[kolom_numerik].head()

"""TAHAP 4: Perhitungan Variabel Penelitian X1, X2, X3, X4"""

# X1: Kondisi Ruang Kelas Baik
df_raw['X1'] = df_raw[['KondisiKelas_SD', 'KondisiKelas_SMP', 'KondisiKelas_SMA', 'KondisiKelas_SMK']].mean(axis=1)

# X2: Kecukupan Sumber Air Bersih
df_raw['X2'] = df_raw[['Air_SD', 'Air_SMP', 'Air_SMA', 'Air_SMK']].mean(axis=1)

# X3: Kepemilikan Toilet Siswa (Terpisah)
df_raw['X3'] = df_raw[['ToiletSD_Terpisah', 'ToiletSMP_Terpisah', 'ToiletSMA_Terpisah', 'ToiletSMK_Terpisah']].mean(axis=1)

# X4: Rasio Murid-Guru
df_raw['X4'] = df_raw[['Rasio_SD', 'Rasio_SMP', 'Rasio_SMA', 'Rasio_SMK']].mean(axis=1)

# X5, X6, X7
df_raw['X5'] = df_raw['Telepon']
df_raw['X6'] = df_raw['Komputer']
df_raw['X7'] = df_raw['Internet']

features = ['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7']

print("7 variabel selesai dihitung")
df_raw[['Provinsi'] + features].head()

"""TAHAP 5: Penanganan Missing Value"""

print("Missing values sebelum ditangani:")
print(df_raw[features].isnull().sum())

# Ganti missing value pada X6 (Komputer) dengan mean
if df_raw['X6'].isnull().sum() > 0:
    mean_komputer = df_raw['X6'].mean(skipna=True)
    print(f"\nMean X6 (Komputer): {mean_komputer:.2f}")
    df_raw['X6'] = df_raw['X6'].fillna(mean_komputer)

print("\nMissing values setelah ditangani:")
print(df_raw[features].isnull().sum())

"""Dataset Final"""

df = df_raw[['Provinsi'] + features].copy()

print(f"Dataset final: {df.shape[0]} provinsi, {df.shape[1]} kolom")
df.head(38)

"""TAHAP 6: Eksplorasi Data (EDA)

Statistik Deskriptif
"""

print("\n=== Statistik Deskriptif ===")
print(df[features].describe().round(2))

"""Visualisasi Histogram"""

plt.figure(figsize=(12, 10))
for i, col in enumerate(features, 1):
    plt.subplot(3, 3, i)
    plt.hist(df[col], bins=15, edgecolor='black', color='skyblue')
    plt.xlabel('Nilai')
    plt.ylabel('Frekuensi')
    plt.title(f'Histogram {col}')
plt.tight_layout()
plt.show()

"""TAHAP 7: Normalisasi Data"""

data = df[features].copy()

scaler = MinMaxScaler()
data_normalized = scaler.fit_transform(data)
data_normalized = pd.DataFrame(data_normalized, columns=features)

print("Data berhasil dinormalisasi (rentang 0-1)")
data_normalized.head(40)

"""TAHAP 8: Penentuan Jumlah Cluster Optimal

Metode Elbow
"""

wcss = []
K_range = range(2, 11)

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(data_normalized)
    wcss.append(kmeans.inertia_)
    print(f"k = {k}: WCSS = {kmeans.inertia_:.2f}")

plt.figure(figsize=(8, 5))
plt.plot(K_range, wcss, 'bo-', linewidth=2, markersize=8)
plt.xlabel('Jumlah Cluster (k)')
plt.ylabel('WCSS')
plt.title('Metode Elbow untuk Menentukan k Optimal')
plt.grid(True)
plt.show()

"""Metode Silhouette Coefficient"""

silhouette_scores = []
for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(data_normalized)
    sil = silhouette_score(data_normalized, labels)
    silhouette_scores.append(sil)
    print(f"k = {k}: Silhouette = {sil:.4f}")

plt.figure(figsize=(8, 5))
plt.plot(K_range, silhouette_scores, 'ro-', linewidth=2, markersize=8)
plt.xlabel('Jumlah Cluster (k)')
plt.ylabel('Silhouette Score')
plt.title('Metode Silhouette untuk Menentukan k Optimal')
plt.grid(True)
plt.show()

optimal_k = 3
print(f"\nJumlah cluster optimal: k = {optimal_k}")

"""TAHAP 9: Implementasi Algoritma K-Means Clustering"""

kmeans_final = KMeans(n_clusters=optimal_k, random_state=42, n_init=10)
df['Cluster'] = kmeans_final.fit_predict(data_normalized)

print(f"Clustering selesai dengan {optimal_k} cluster")
print("\nDistribusi anggota per cluster:")
print(df['Cluster'].value_counts().sort_index())

"""TAHAP 10: Evaluasi Kualitas Cluster"""

dbi_score = davies_bouldin_score(data_normalized, df['Cluster'])
sil_score = silhouette_score(data_normalized, df['Cluster'])

print("\n=== Evaluasi Kualitas Cluster ===")
print(f"Davies-Bouldin Index: {dbi_score:.4f} (semakin mendekati 0 semakin baik)")
print(f"Silhouette Score: {sil_score:.4f} (>0.5 = baik, >0.7 = sangat baik)")

"""TAHAP 11: Analisis Karakteristik Cluster

Profil Rata-rata per Cluster
"""

cluster_profiles = df.groupby('Cluster')[features].mean()
print("\n=== Profil Rata-rata per Cluster ===")
print(cluster_profiles.round(2))

"""Anggota Provinsi per Cluster"""

print("\n=== Anggota Provinsi per Cluster ===")
for cluster in range(optimal_k):
    anggota = df[df['Cluster'] == cluster]['Provinsi'].tolist()
    print(f"\nCluster {cluster} ({len(anggota)} provinsi):")
    print(', '.join(anggota))

"""TAHAP 12: Visualisasi Hasil

Radar Plot
"""

categories = features
fig = go.Figure()

for cluster in range(optimal_k):
    fig.add_trace(go.Scatterpolar(
        r=cluster_profiles.loc[cluster].values,
        theta=categories,
        fill='toself',
        name=f'Cluster {cluster}'
    ))

fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, 100])),
    title=f'Profil Cluster Pendidikan Digital dan Fasilitas Sekolah (k={optimal_k})',
    showlegend=True
)
fig.show()

"""Scatter Plot PCA"""

pca = PCA(n_components=2)
principal_components = pca.fit_transform(data_normalized)

plt.figure(figsize=(12, 8))
scatter = plt.scatter(principal_components[:, 0], principal_components[:, 1],
                      c=df['Cluster'], cmap='viridis', s=100)
plt.xlabel('Komponen Utama 1')
plt.ylabel('Komponen Utama 2')
plt.title('Cluster Plot Fasilitas Sekolah dan Pendidikan Digital per Provinsi')
plt.colorbar(scatter, label='Cluster')
for i, provinsi in enumerate(df['Provinsi']):
    plt.annotate(provinsi, (principal_components[i, 0], principal_components[i, 1]), fontsize=8)
plt.show()